name: Document Conversion

on: push

jobs:
  convert_to_pdf:
    name: Convert via Pandoc
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: mkdir output
      - uses: hubgit/pandoc@master
        with:
          args: "--pdf-engine=xelatex --output=output/README.pdf README.md"
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
